services:
  service:
    build:
      context: .
      dockerfile: apps/service/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - apps/service/.env
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
